baseurl = "https://danielreispereira.netlify.com/"
languageCode = "en-us"
title = "Daniel 3"
# Enable comments by entering your Disqus shortname
disqusShortname = "drpnetlify"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-hikari-theme"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Daniel"
	description = "Personal random stuff"
	copyright = "POWERED BY [HUGO](//gohugo.io) - THEME: [HIKARI](//github.com/digitalcraftsman/hugo-hikari-theme) - © DANIEL "

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Hi, I'm Daniel"
	bio = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex, pariatur!"
	subscribe = "Subscribe"
	followme = "Follow me on"

	# Enable Google search
	search_enabled = true
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "//github.com/danielreispereira"

	[[params.offcanvas.socialnetworks]]
		name = "Twitter"
		url = "//twitter.com/spf13"
